name: Deploy TTS API

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
    
    - name: Install dependencies
      run: npm install
    
    - name: Create temp directory
      run: mkdir -p temp
    
    - name: Run tests (if any)
      run: |
        if [ -f "package.json" ] && grep -q "\"test\"" package.json; then
          npm test || echo "No tests found"
        fi
    
    - name: Build application
      run: |
        echo "Application ready for deployment"
        node --version
        npm --version
        ffmpeg -version
    
    # Option 1: Deploy to Render.com
    - name: Deploy to Render
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
      run: |
        if [ ! -z "$RENDER_API_KEY" ]; then
          curl -X POST "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys" \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json"
          echo "Deployed to Render successfully!"
        else
          echo "Render credentials not configured. Skipping deployment."
        fi
    
    # Option 2: Deploy to Railway
    - name: Deploy to Railway
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: |
        if [ ! -z "$RAILWAY_TOKEN" ]; then
          npm install -g @railway/cli
          railway link ${{ secrets.RAILWAY_PROJECT_ID }} || echo "Railway not configured"
          railway up || echo "Railway deployment skipped"
        else
          echo "Railway credentials not configured. Skipping deployment."
        fi
    
    - name: Deployment Summary
      run: |
        echo "✅ Build completed successfully!"
        echo "📦 Dependencies installed"
        echo "🎵 FFmpeg configured"
        echo "🚀 Ready for deployment"
